### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (640, 2) + inhomogeneous part.

### ISSUE THREAD

**Issue by yangyuxiao-sjtu** [bhiziroglu/Language-as-an-Abstraction-for-Hierarchical-Deep-Reinforcement-Learning#3]
when I simply run the main.py, the error occurs
Traceback (most recent call last):
  File "/home/yuxiaoyang/Lang/Lang/main.py", line 164, in <module>
    env = ClevrEnv(action_type="perfect", obs_type='order_invariant', direct_obs=True, use_subset_instruction=True)
  File "/home/yuxiaoyang/Lang/Lang/clevr_robot_env/clevr_robot_env/env.py", line 138, in __init__
    train, test = load_utils.create_train_test_question_split()
  File "/home/yuxiaoyang/Lang/Lang/clevr_robot_env/clevr_robot_env/utils/load_utils.py", line 48, in create_train_test_question_split
    aq = np.array(all_questions)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (640, 2) + inhomogeneous part.
Does anyone know how to fix it?

**Comment by nico1995lee** [comment]
Same problem.
Do you fix it?
